### ISSUE TITLE
The Mod Legacy4J crashes when starting in Pojavlauncher (Minecraft Java for Android)

### ISSUE THREAD

**Issue by Keno3704** [Permdog99/Legacy-Remade#2]
Just start both the Legacy4J Mod and the modpack, the game crashes before you can open the start menu the last thing you see is the Xbox, Mojang or the age

Here is the Launcher Logoutput when starting the Modpack, it was not possible to copy everything because when the game crashes it is very fast and it is almost impossible to copy 

--------- beginning of system

--------- beginning of main

I/jrelog  (14011): dlopen libxhook.so failed: dlopen failed: library "libxhook.so" not found

I/jrelog  (14081): dlopen libxhook.so failed: dlopen failed: library "libxhook.so" not found
I/jrelog  (14124): dlopen libxhook.so failed: dlopen failed: library "libxhook.so" not found

Initialising gl4es
v1.1.5 built on Sep 27 2023 17:42:09
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
Targeting OpenGL 2.1
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
glX Will try to recycle EGL Surface
Current folder is:/
I/jrelog  (14124): dlopen libgl4es_114.so success

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.firefly/cache
Added custom env: AWTSTUB_WIDTH=1512
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch.firefly-9lLcYqz3O00skJbBqLWb-A==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.firefly/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: POJAV_BETA_RENDERER=opengles2
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch.firefly-9lLcYqz3O00skJbBqLWb-A==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=756
I/jrelog  (14124): dlopen libgl4es_114.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjli.so success

I/jrelog  (14124): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libverify.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjava.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnet.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnio.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfreetype.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfontmanager.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libprefs.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libextnet.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjava.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libdt_socket.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libsctp.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjsig.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmanagement.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libsyslookup.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnet.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjdwp.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libj2gss.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjli.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfreetype.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/librmi.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libverify.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmanagement_agent.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libj2pkcs11.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmlib_image.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjimage.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjawt.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnio.so success
I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libzip.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/liblcms.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt_xawt.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libinstrument.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/server/libjsig.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjavajpeg.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfontmanager.so success

I/jrelog  (14124): dlopen /data/user/0/net.kdt.pojavlaunch.firefly/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjaas.so success

I/jrelog  (14124): dlopen /data/app/net.kdt.pojavlaunch.firefly-9lLcYqz3O00skJbBqLWb-A==/lib/arm64/libopenal.so success

I/jrelog  (14124): Done processing args

I/jrelog  (14124): Found JLI lib
I/jrelog  (14124): Calling JLI_Launch

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(Unknown Source)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(Unknown Source)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(Unknown Source)
	at java.base/java.lang.System.initPhase3(Unknown Source)
Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Failed to inject cache!
java.lang.ClassNotFoundException: java.net.InetAddress$CacheEntry
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.lang.Class.forName(Unknown Source)
	at git.artdeell.arcdns.CacheUtil_J8.getConstructorOfInetAddress$CacheEntry(CacheUtil_J8.java:45)
	at git.artdeell.arcdns.CacheUtil_J8.newCacheEntry(CacheUtil_J8.java:32)
	at git.artdeell.arcdns.CacheUtil_J8.setInetAddressCache(CacheUtil_J8.java:20)
	at git.artdeell.arcdns.ArcDNSInjectorAgent.premain(ArcDNSInjectorAgent.java:12)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
	Suppressed: java.lang.ClassNotFoundException: java.net.InetAddress$CachedAddresses
		at java.base/java.net.URLClassLoader.findClass(Unknown Source)
		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
		at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Unknown Source)
		at java.base/java.lang.Class.forName(Unknown Source)
		at git.artdeell.arcdns.CacheUtil_J9.getConstructorOfInetAddress$CachedAddresses(CacheUtil_J9.java:42)
		at git.artdeell.arcdns.CacheUtil_J9.newCachedAddresses(CacheUtil_J9.java:30)
		at git.artdeell.arcdns.CacheUtil_J9.setInetAddressCache(CacheUtil_J9.java:20)
		at git.artdeell.arcdns.ArcDNSInjectorAgent.premain(ArcDNSInjectorAgent.java:9)
		... 4 more
2024-06-09 10:51:19,181 main ERROR appender Console has no parameter that matches element Policies
[10:51:20] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.11
[10:51:22] [main/WARN]: Warnings were found!
 - Mod 'Dynamic FPS' (dynamic_fps) 3.4.3 recommends any version of quilt_loader, which is missing!
	 - You should install any version of quilt_loader for the optimal experience.
 - Mod 'Legacy4J' (legacy) 1.6.7 conflicts with any version of mod 'Sodium Extra' (sodium-extra), which is present with the following versions: 0.5.4+mc1.20.4-build.116!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Legacy4J' (legacy) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
 - Mod 'Legacy4J' (legacy) 1.6.7 conflicts with any version of mod 'Reese's Sodium Options' (reeses-sodium-options), which is present with the following versions: 1.7.2+mc1.20.4-build.102!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Legacy4J' (legacy) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
 - Mod 'Legacy4J' (legacy) 1.6.7 conflicts with any version of mod 'Mod Menu' (modmenu), which is present with the following versions: 9.2.0-beta.2!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Legacy4J' (legacy) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
 - Mod 'Polytone' (polytone) 1.20.4-1.18.10 conflicts with any version of mod 'Sodium' (sodium), which is present with the following versions: 0.5.8+mc1.20.4!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Polytone' (polytone) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
[10:51:22] [main/INFO]: Loading 171 mods:
	- architectury 11.1.17
	- ash_api 20.4.0
	- balm-fabric 9.0.9
	- bestylewither 1.7.0
	- betterhurtcam 1.7.0+mc1.20.3
	- betterimpaling 2.0.7
	- betterpingdisplay 1.1.1
	- boatiview 0.0.5
	- bobby 5.1.0+mc1.20.4
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- bookshelf 23.0.8
	- chatsigninghider 1.20.4-1.0.5
	- clientsidenoteblocks 2.7
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- cool_elytra 1.5
	   \-- midnightlib 1.5.3
	- craftpresence 2.3.9
	- craterlib 1.1.0
	- customwindowtitle 1.2.0
	- debugify 1.20.4+1.1
	- deepslatetweaks 1.2
	- disable_custom_worlds_advice 5.0
	- dynamic_fps 3.4.3
	- e4mc_minecraft 5.0.0
	- emojitype 2.2.3+1.20.4
	- emuno 1.1.1
	- entity_model_features 2.0.2
	- entity_texture_features 6.0.1
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.5
	- fabric-api 0.97.1+1.20.4
	   |-- fabric-api-base 0.4.37+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.17+78d798af4f
	   |-- fabric-block-api-v1 1.0.17+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.5+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.47+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.8+78d798af4f
	   |-- fabric-command-api-v1 1.2.42+f71b366f4f
	   |-- fabric-command-api-v2 2.2.21+78d798af4f
	   |-- fabric-commands-v0 0.2.59+df3654b34f
	   |-- fabric-containers-v0 0.1.87+df3654b34f
	   |-- fabric-content-registries-v0 5.0.16+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.11+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.5+5c0133444f
	   |-- fabric-dimensions-v1 2.1.63+6605d1a84f
	   |-- fabric-entity-events-v1 1.6.2+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.2+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
	   |-- fabric-game-rule-api-
v1 1.0.47+78d798af4f
	   |-- fabric-item-api-v1 2.3.0+bcdd12964f
	   |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
	   |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
	   |-- fabric-keybindings-v0 0.2.40+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.10+78d798af4f
	   |-- fabric-message-api-v1 6.0.6+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
	   |-- fabric-models-v0 0.4.8+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.8+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.1.0+dba1195c4f
	   |-- fabric-particles-v1 1.1.8+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.21+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.20+ee30b13a4f
	   |-- fabric-renderer-api-v1 3.2.5+78d798af4f
	   |-- fabric-renderer-indigo 1.5.6+d331d3144f
	   |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
	   |-- fabric-rendering-v0 1.1.57+df3654b34f
	   |-- fabric-rendering-v1 3.2.1+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
	   |-- fabric-screen-api-v1 2.0.18+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.56+78d798af4f
	   |-- fabric-sound-api-v1 1.0.18+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.12+90f2d7b14f
	   \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_j
etbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- fabricskyboxes 0.7.3+mc1.20.2
	- ferritecore 6.0.3
	- forgeconfigapiport 20.4.3
	- fsb-interop 1.3.6+mc1.20.2-build.52
	- goldenagecombat 20.4.2
	- immediatelyfast 1.2.17+1.20.4
	   \-- net_lenni0451_reflect 1.3.3
	-

**Comment by Permdog99** [comment]
If this is something that happens with only Legacy4J installed, then it needs to be reported to them. I can only change the mods installed and the configs, not the mod itself.

Though I'm not surprised it isn't working because from what I understand of Legacy4J, it requires certain things that only exist on PC

**Comment by Permdog99** [comment]
Closing this issue due to inactivity and not being related to Legacy Remade
